import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.


		int sum_of_children = 0;
		int num_of_families_with_2_children = 0;
		int num_of_families_with_3_children = 0;
		int num_of_families_with_4_or_more_children = 0;
		for( int i = 1 ; i <= T; i++ ) {
			boolean boy = false;
			boolean girl = false;
			int number_of_children = 0;
			while (boy == false || girl == false){
				double rnd = generator.nextDouble();
				number_of_children++;
				if (rnd < 0.5){
					boy = true;
				}
				else {
					girl = true;
				}
			}
			sum_of_children = sum_of_children + number_of_children;
			switch(number_of_children){
				case 2:
					num_of_families_with_2_children++;
					break;
				case 3:
					num_of_families_with_3_children++;
					break;
				default:
					num_of_families_with_4_or_more_children++;
					break;
			}
		}
		String most_common_number_of_children = "";
		if (num_of_families_with_2_children > num_of_families_with_3_children) {
			if (num_of_families_with_2_children > num_of_families_with_4_or_more_children) {
				most_common_number_of_children = "2";
			}
			else{
				most_common_number_of_children = "4 or more";
			}
		}
		else if (num_of_families_with_3_children > num_of_families_with_4_or_more_children ){
			most_common_number_of_children = "3";
		}
		else{
			most_common_number_of_children = "4 or more";
		}
		System.out.println("Average: " + ((double)sum_of_children / T) + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + num_of_families_with_2_children);
		System.out.println("Number of families with 3 children: " + num_of_families_with_3_children);
		System.out.println("Number of families with 4 or more children: " + num_of_families_with_4_or_more_children);
		System.out.println("The most common number of children is " + most_common_number_of_children) + ".";

	}
}

		    

